### ISSUE TITLE
packetdrill crashes on raspberry pi 2 with arch linux

### ISSUE THREAD

**Issue by TheAomx** [nplab/packetdrill#101]
While running the sctp-invalid-length test suite on my raspberry pi 2 with Arch Linux installed, the following test-cases are crashing with a core dump:
- sctp-invalid-sack-invalid-empty-content.pkt
- sctp-invalid-shutdown-invalid-too-short-length.pkt

The error message is:

> **\* Error in `packetdrill': free(): invalid next size (fast): 0x0204c4b8 ***
> ======= Backtrace: =========
> /usr/lib/libc.so.6(+0x649a4)[0x76dfd9a4]
> /usr/lib/libc.so.6(+0x6ad2c)[0x76e03d2c]
> /usr/lib/libc.so.6(+0x6b6bc)[0x76e046bc]
> ======= Memory map: ========
> 00010000-00092000 r-xp 00000000 b3:02 418888     /usr/bin/packetdrill
> 000a2000-000a5000 rw-p 00082000 b3:02 418888     /usr/bin/packetdrill
> 02045000-0207e000 rw-p 00000000 00:00 0          [heap]
> 76400000-76421000 rw-p 00000000 00:00 0 
> 76421000-76500000 ---p 00000000 00:00 0 
> 7656c000-7656d000 ---p 00000000 00:00 0 
> 7656d000-76d6c000 rw-p 00000000 00:00 0          [stack:1030]
> 76d6c000-76d88000 r-xp 00000000 b3:02 411158     /usr/lib/libgcc_s.so.1
> 76d88000-76d98000 ---p 0001c000 b3:02 411158     /usr/lib/libgcc_s.so.1
> 76d98000-76d99000 rw-p 0001c000 b3:02 411158     /usr/lib/libgcc_s.so.1
> 76d99000-76ec0000 r-xp 00000000 b3:02 411287     /usr/lib/libc-2.23.so
> 76ec0000-76ed0000 ---p 00127000 b3:02 411287     /usr/lib/libc-2.23.so
> 76ed0000-76ed2000 r--p 00127000 b3:02 411287     /usr/lib/libc-2.23.so
> 76ed2000-76ed3000 rw-p 00129000 b3:02 411287     /usr/lib/libc-2.23.so
> 76ed3000-76ed6000 rw-p 00000000 00:00 0 
> 76ed6000-76ed8000 r-xp 00000000 b3:02 418957     /usr/lib/libsctp.so.1.0.16
> 76ed8000-76edf000 ---p 00002000 b3:02 418957     /usr/lib/libsctp.so.1.0.16
> 76edf000-76ee0000 r--p 00001000 b3:02 418957     /usr/lib/libsctp.so.1.0.16
> 76ee0000-76ee1000 rw-p 00002000 b3:02 418957     /usr/lib/libsctp.so.1.0.16
> 76ee1000-76ee7000 r-xp 00000000 b3:02 411142     /usr/lib/librt-2.23.so
> 76ee7000-76ef6000 ---p 00006000 b3:02 411142     /usr/lib/librt-2.23.so
> 76ef6000-76ef7000 r--p 00005000 b3:02 411142     /usr/lib/librt-2.23.so
> 76ef7000-76ef8000 rw-p 00006000 b3:02 411142     /usr/lib/librt-2.23.so
> 76ef8000-76f0e000 r-xp 00000000 b3:02 411166     /usr/lib/libpthread-2.23.so
> 76f0e000-76f1d000 ---p 00016000 b3:02 411166     /usr/lib/libpthread-2.23.so
> 76f1d000-76f1e000 r--p 00015000 b3:02 411166     /usr/lib/libpthread-2.23.so
> 76f1e000-76f1f000 rw-p 00016000 b3:02 411166     /usr/lib/libpthread-2.23.so
> 76f1f000-76f21000 rw-p 00000000 00:00 0 
> 76f21000-76f41000 r-xp 00000000 b3:02 411095     /usr/lib/ld-2.23.so
> 76f41000-76f43000 rw-p 00000000 00:00 0 
> 76f4e000-76f50000 rw-p 00000000 00:00 0 
> 76f50000-76f51000 r--p 0001f000 b3:02 411095     /usr/lib/ld-2.23.so
> 76f51000-76f52000 rw-p 00020000 b3:02 411095     /usr/lib/ld-2.23.so
> 7ebe7000-7ec08000 rw-p 00000000 00:00 0          [stack]
> 7ee07000-7ee08000 r-xp 00000000 00:00 0          [sigpage]
> 7ee08000-7ee09000 r--p 00000000 00:00 0          [vvar]
> 7ee09000-7ee0a000 r-xp 00000000 00:00 0          [vdso]
> ffff0000-ffff1000 r-xp 00000000 00:00 0          [vectors]

I think that the issue is, that the handling of chunks like this
- +0.0 < sctp: CHUNK[type=3, flgs=0, len=4, val=[]]
- +0.0 < sctp: CHUNK[type=7, flgs=0, len=4, val=[]]

is not correct and therefore a not allocated pointer is freed. Maybe the other platforms are setting this pointer to NULL implicitly and the armv7 doesnt?

**Comment by tuexen** [comment]
Seems to run fine on amd64 with valgrind. Possibly fixed in the meantime.
