### ISSUE TITLE
Fail to compile on Linux ppc64/ppc64le machine

### ISSUE THREAD

**Issue by jijianwen** [nplab/packetdrill#136]
Hi, when compiling packetdrill on ppc64/ppc64le machines with RHEL-7.4 installed, got the following error messages, please help check it. Thanks!

[root@ nplab]# uname -m
ppc64

[root@ nplab]# uname -r
3.10.0-693.el7.ppc64

[root@ nplab]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/ppc64-redhat-linux/4.8.5/lto-wrapper
Target: ppc64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-ppc64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-ppc64-redhat-linux/cloog-install --enable-gnu-indirect-function --enable-secureplt --with-long-double-128 --with-cpu-32=power7 --with-tune-32=power7 --with-cpu-64=power7 --with-tune-64=power7 --build=ppc64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)

[root@ibm-p740-01-lp3 nplab]# 
cc -g -Wall -Werror -Wno-unknown-warning-option -Wno-address-of-packed-member   -c -o packetdrill.o packetdrill.c
In file included from packetdrill.c:25:0:
types.h:78:13: error: conflicting types for ‘__u64’
 typedef u64 __u64;
             ^
In file included from /usr/include/asm/types.h:25:0,
                 from /usr/include/linux/types.h:4,
                 from /usr/include/netinet/sctp.h:37,
                 from platforms.h:38,
                 from types.h:43,
                 from packetdrill.c:25:
/usr/include/asm-generic/int-l64.h:29:23: note: previous declaration of ‘__u64’ was here
 typedef unsigned long __u64;
                       ^
In file included from packetdrill.c:25:0:
types.h:85:13: error: conflicting types for ‘__le64’
 typedef u64 __le64;
             ^
In file included from /usr/include/netinet/sctp.h:37:0,
                 from platforms.h:38,
                 from types.h:43,
                 from packetdrill.c:25:
/usr/include/linux/types.h:31:25: note: previous declaration of ‘__le64’ was here
 typedef __u64 __bitwise __le64;
                         ^
In file included from packetdrill.c:25:0:
types.h:86:13: error: conflicting types for ‘__be64’
 typedef u64 __be64;
             ^
In file included from /usr/include/netinet/sctp.h:37:0,
                 from platforms.h:38,
                 from types.h:43,
                 from packetdrill.c:25:
/usr/include/linux/types.h:32:25: note: previous declaration of ‘__be64’ was here
 typedef __u64 __bitwise __be64;
                         ^
cc1: error: unrecognized command line option "-Wno-address-of-packed-member" [-Werror]
cc1: error: unrecognized command line option "-Wno-unknown-warning-option" [-Werror]

**Comment by tuexen** [comment]
It seems you are using a very old kernel (3.10) which uses `long int` as the type for `__s64`. It also seems that newer kernels use `long long int` for it and this is what the `packetdrill` sources are using. Can you update to a more recent linux kernel source tree?

If not, one would have to change the definitions in `types.h` to match the ones on your platform and also fix some format strings for printing `__u64` and `__s64` from `%llu` to `%lu` and `%lld` to `%ld` as the compiler will find them. You can try that and report if that works.

**Comment by jijianwen** [comment]
It seems that my Linux system has already defined __u64/__le64/__be64. I did the following modification in types.h and it works now.

diff --git a/gtests/net/packetdrill/types.h b/gtests/net/packetdrill/types.h
index 21b124a..a2397fc 100644
--- a/gtests/net/packetdrill/types.h
+++ b/gtests/net/packetdrill/types.h
@@ -75,15 +75,15 @@ typedef signed long long s64;
 typedef u8 __u8;
 typedef u16 __u16;
 typedef u32 __u32;
-typedef u64 __u64;
+//typedef u64 __u64;
 
 /* We also use kernel-style names for endian-specific unsigned types. */
 typedef u16 __le16;
 typedef u16 __be16;
 typedef u32 __le32;
 typedef u32 __be32;
-typedef u64 __le64;
-typedef u64 __be64;
+//typedef u64 __le64;
+//typedef u64 __be64;
 
 typedef u16 __sum16;
 typedef u32 __wsum;

**Comment by tuexen** [comment]
Interesting. No problems (compile warnings or errors) regarding printf-format strings?

**Comment by jijianwen** [comment]
No compile warnings or errors found.
I'd like to test your patch:)

**Comment by tuexen** [comment]
Please try:
```
diff --git a/gtests/net/packetdrill/types.h b/gtests/net/packetdrill/types.h
index 21b124a..8a9808e 100644
--- a/gtests/net/packetdrill/types.h
+++ b/gtests/net/packetdrill/types.h
@@ -36,6 +36,9 @@
 #include <stdio.h>
 #include <string.h>
 #include <arpa/inet.h>
+#if defined(linux)
+#include <linux/types.h>
+#endif
 #include <netinet/in.h>
 #include <sys/socket.h>
 #include <sys/time.h>
@@ -72,6 +75,7 @@ typedef signed short s16;
 typedef signed int s32;
 typedef signed long long s64;
 
+#if !defined(linux)
 typedef u8 __u8;
 typedef u16 __u16;
 typedef u32 __u32;
@@ -87,6 +91,7 @@ typedef u64 __be64;
 
 typedef u16 __sum16;
 typedef u32 __wsum;
+#endif
 
 typedef u8 bool;
 enum bool_t {
```

**Comment by jijianwen** [comment]
Hi tuexen, tested your patch on x86_64/ppc64/ppc64le/aarch64 machines with Linux kernel 4.11.0 installed. All are good!

**Comment by tuexen** [comment]
Thanks for testing. I committed the fix.
