### ISSUE TITLE
Segmentation fault happened when running latest packetdrill on Linux

### ISSUE THREAD

**Issue by jijianwen** [nplab/packetdrill#139]
Hi, I got the following error message:
[root@dhcp-12-237 packetdrill]# ./packetdrill tests/linux/sctp/sctp_socket_options.pkt
Segmentation fault (core dumped)

After investigation, I found it was caused by the  following call trace
  local_netdev_new()
          packet_socket_set_filter(netdev->psock, NULL, &config->live_local_ip)  
             the second paramter is NULL passed to packet_socket_set_filter, and the following codes will dereference the NULL

170         /* Fill in the client-side ethernet address to look for. */
171         bpfcode.filter[1].k = ((client_ether[2] << 24) |
172                                (client_ether[3] << 16) |
173                                (client_ether[4] << 8)  |
174                                (client_ether[5]));
175         bpfcode.filter[3].k = ((client_ether[0] << 8)  |
176                                (client_ether[1]));

Please take a look and fix it.

**Comment by tuexen** [comment]
Thanks for reporting the issue and sorry for breaking it.
