### ISSUE TITLE
open utun device: Operation not permitted

### ISSUE THREAD

**Issue by ligurio** [nplab/packetdrill#146]
On running packetdrill I am getting error:
`2020-01-16 04:13:44,401 [INFO] open utun device: Operation not permitted`

How to fix it?

Mac OS Mojave

**Comment by tuexen** [comment]
Are you running it with `sudo`? Opening a device required root privileges. I just checked that running it with sudo works on Catalina. Don't have access to a Mojave system anymore.

**Comment by ligurio** [comment]
@tuexen Oh, it is so obvious! I thought command executed in CI with root privileges, but it was not so.
Thanks!
