### ISSUE TITLE
Injecting a heartbeat-ack with custom heartbeat-information not possible

### ISSUE THREAD

**Issue by TheAomx** [nplab/packetdrill#78]
The following chunks are simply not injected like specified by packetdrill:
```
+0.0 < sctp: CHUNK[type=5, flgs=0, len=12, val=[0x00, 0x01, 0x00, 0x02, 0x00, 0x01, 0x02, 0x03]]
+0.0 < sctp: CHUNK[type=5, flgs=0, len=12, val=[0x00, 0x01, 0xFF, 0xFF, 0x00, 0x01, 0x02, 0x03]]
```
packetdrill injects a heartbeat-information-chunk but the heartbeat-information of the previously sniffed heartbeat-packet gets injected, which should not be when using a generic chunk.

**Comment by tuexen** [comment]
Fixed.
